name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . -t my-fastapi-app

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 my-fastapi-app

      - name: Wait for the application to start
        run: |
          sleep 10

      - name: Test the application
        run: |
          curl -f http://localhost:8000/ || exit 1

      - name: Stop Docker container
        run: |
          docker ps -q --filter "ancestor=my-fastapi-app" | xargs docker stop
          docker ps -aq --filter "ancestor=my-fastapi-app" | xargs docker rm